### ISSUE TITLE
Suggestion: Mod support for logicates and red bits

### ISSUE THREAD

**Issue by simeeow** [replaceitem/integrated-circuit#13]

**Comment by replaceitem** [comment]
*I'm going to assume you mean placing modded components inside an IC*

I want to keep the component selection simple and close to vanilla, and adding more advanced gates and circuits kind of defeats the idea of an integrated circuit. Using such advanced components inside circuits is something i would rather have implemented by #3, so you would create your own - say a toggle latch - in an IC, and use that in another IC.
