### ISSUE TITLE
Crash in 1.19.2

### ISSUE THREAD

**Issue by gundami** [replaceitem/integrated-circuit#17]
Game will crash when i right click the circuit with lever and redstone lamp.

**Comment by replaceitem** [comment]
Can you provide a crash log?

**Comment by gundami** [comment]
crash log: https://pastebin.com/bwEwkZGE

**Comment by replaceitem** [comment]
This is fixed starting from version 1.1.4, ehich is only for 1.19.3 upwards. Is it possible for you to update?

**Comment by gundami** [comment]
sadly, my modpack is 1.19.2 version. can you update the mod with 1.19.2?

**Comment by replaceitem** [comment]
Alright, i added `integrated-circuit-1.1.1-crashfix.jar` to [1.1.1](https://modrinth.com/mod/integrated-circuit/version/1.1.1) where this should be fixed
