### ISSUE TITLE
Ask: Why integrated circuit NBT data lost when broken? thus cannot be copied

### ISSUE THREAD

**Issue by lascrusade** [replaceitem/integrated-circuit#18]
Recently, i tried to modify integrated circuit. But, when i break it in order to copy it in crafting table (in survival), the NBT data lost and i get empty integrated circuit instead. 

Does not matter if i use silk touch pickaxe, NBT data still gone. The only way to persists NBT data is to use creative mode and press ctrl + MMB

**Comment by replaceitem** [comment]
Hmm pretty sure this used to work. Might have broke though. What version are you using?
