### ISSUE TITLE
Curseforge?

### ISSUE THREAD

**Issue by simeeow** [replaceitem/integrated-circuit#2]
I have a modpack and this seems like the perfect mod for one thing I want, but it’s a curseforge pack.

**Comment by replaceitem** [comment]
I much prefer Modrinth, and don't want to maintain two platforms, sorry.

**Comment by simeeow** [comment]
Can I apply it to the approved non curseforge mods list?

**Comment by replaceitem** [comment]
I'm not too into Modpacks to know what that means, but if you are referring to permission, then yes, feel free to include it.
