### ISSUE TITLE
Crash When Teleporting Away With Waystones Mod

### ISSUE THREAD

**Issue by nightstick24** [replaceitem/integrated-circuit#21]
I'm using Integrated Circuits on a modded 1.20.1 server running Fabric, using Version 1.3.1 of Integrated Circuits. On this server we've also got the Waystones mod, v14.0.1. When you teleport away from a chunk with an Integrated Circuit through the warp stone, warp plate, or a Waystone it immediately crashes the game. It seems to be a problem with unloading the Integrated Circuits too quickly or in an unexpected way. My crash logs are linked below.

Thanks!

https://mclo.gs/JDP9Xoq
https://mclo.gs/oLKw9Cf

**Comment by replaceitem** [comment]
Fixed in [1.3.4](https://modrinth.com/mod/integrated-circuit/version/1.3.4)
