### ISSUE TITLE
Outside comparator input

### ISSUE THREAD

**Issue by lukescott** [replaceitem/integrated-circuit#24]
If you place a comparator next to the input, it doesn't read the chest comparator output value.

This does make sense because the arrows show a Redstone dust line on them, and it consumes 1 power level.

However, it would be nice if you could place a comparator on that colored square to read the comparator output.

This mod has similar looking device, although you write code rather than placing blocks:

https://github.com/stfwi/redstonepen/tree/master/documentation/redstone-logic-control

They use R for the Red input that represents the normal Redstone power level. However, they have R.CO that allows you to get the comparator output value of blocks that provide it, such as chests and hoppers. Perhaps you could use a similar mechanism to get the comparator output value?

![Minecraft_ 1 20 4 - Singleplayer 12_22_2023 10_32_59 PM](https://github.com/replaceitem/integrated-circuit/assets/486224/ef648fa8-fadb-4c33-b139-810029463621)

![Minecraft_ 1 20 4 - Singleplayer 12_22_2023 10_33_39 PM](https://github.com/replaceitem/integrated-circuit/assets/486224/d981b4bc-47cd-4422-a800-622acb547bf1)
![Minecraft_ 1 20 4 - Singleplayer 12_22_2023 10_33_57 PM](https://github.com/replaceitem/integrated-circuit/assets/486224/69ff7e34-72c3-44d4-8a96-9294e441bb0e)

**Comment by replaceitem** [comment]
I think it makes sense and is more intuitive to only accept redstone signal, and not "read" comparator levels through the circuit. So i would prefer to keep it like this.

**Comment by lukescott** [comment]
Ah, I was hoping it would be possible in conjunction with #25 as it would allow for a more compact sorter design. (Just like I can do w/ Red Pen mod, just without the code syntax; IC is more physical and vanilla like).

A compact design can still happen without and w/ #25, it just takes up 2x2 (IC behind comparator, IC powers/unpowers block underneath w/ a torch attached). vs w/ built in comparator, 1x1 without the torch outside the IC needed.

In general, I thought it would be neat to turn the R/B/Y/G squares into regular squares like the 15x15. By doing so, you could place a Redstone dust and have it be bi-directional (without the arrow). Or you could place a comparator and take the CO output from a Chest/Hopper as input. And then add a new component that controls input/output direction like those edge squares do, but it can be used anywhere in the 15x15 grid.

(I find the arrows somewhat weird because there isn't an equivalent vanilla component; But if there is a need for it, why not have it be a special IC component that can be placed anywhere).

**Comment by replaceitem** [comment]
I do like the idea of having inputs be colored floor tiles where you could place dust on top. Eliminating the input/output concept would be nice too. The reason i didn't originally do this is because the way the circuit is ticked. It has it's own update scheduler that is ran every tick inside the block entity, and doesnt work with updates from outer redstone. Maybe i will get to reworking that at some point.
