### ISSUE TITLE
Crashes instantly upon placing integrated circuit

### ISSUE THREAD

**Issue by dhasial** [replaceitem/integrated-circuit#30]
MC version 1.19.2
Modpack: StaTech Industry
Mod version: 1.1.1

`latest.log` containing the crash (starts at line 10750)
https://gist.github.com/dhasial/bb8cb9e7539148f22bde81337d27677b

**Comment by replaceitem** [comment]
There is a crashfix file uploaded to the 1.1.1 release of the mod: https://modrinth.com/mod/integrated-circuit/version/1.1.1
It should work if you swap that out

**Comment by replaceitem** [comment]
Does it work with only the integrated circuit mod without any other mods?

**Comment by dhasial** [comment]
It does not. I made a quick 1.19.2 instance with the same Fabric loader version; same behaviour.
