### ISSUE TITLE
Improve Circuit editing keybinds/mouse controls

### ISSUE THREAD

**Issue by replaceitem** [replaceitem/integrated-circuit#4]
This includes
* Seperate keybinds for placing/breaking/picking from vanilla
* Invert scroll direction (potetial need for ClothConfig?)

**Comment by RevolvingMadness** [comment]
More improvements:
Swap left and right mouse button controls
'r' key to rotate

**Comment by replaceitem** [comment]
Swapping place/remove would be possible if they are assignable in the keybinds. An additional option rotorate besides scrolling also makes sense.
